#version: '3.8'
#
#volumes:
#    postgres:
#
#services:
#  postgres:
#    container_name: demo_postgres
#    image: "postgres:15"
#    environment:
#      POSTGRES_USER: "user"
#      POSTGRES_PASSWORD: "pass"
#      PGDATA: "/data/postgres"
#    volumes:
#       - postgres:/data/postgres
#    ports:
#      - "5432:5432"
#    restart: unless-stopped